@Library('pipeline-library')
@Library('indy-pipeline-library')
import politie.jenkins.*
import org.commonjava.indy.jenkins.pipeline.git.*

def gitOperation = new GitOperation()
def builder = new JenkinsPipelineSteps()
builder.initialize()

 node('nos-indy-release-node-1'){
   stage('git clone'){
    git url: 'https://github.com/bxf12315/logback-elasticsearch-appender.git'
    }

    stage('mvn test'){
          def ss = builder.getCommitId()

          echo ss
    }

    stage('mvn build'){
        
     sh 'cd '
     sh '''mvn clean install -DskipTests'''
    }
 stage('release'){
      sh('git config -l')
      sh('id')
     // gitOperation.createTag("1.9.3","test")
      gitOperation.pushTag("1.9.3","origin")
        echo "deploy ......" 
 }
}

